### ISSUE TITLE
Regarding License

### ISSUE THREAD

**Issue by Rembane** [cygni/snakebot-client-rust#5]
Hi! 

Can you put an open source license on this? BSD perhaps? It would make things so much easier!

**Comment by mbark** [comment]
Will do when I have time (a bit embarrassing that I missed that), however I encourage you to create a PR with some decent `LICENSE` (BSD perhaps?)!

**Comment by Rembane** [comment]
No worries, I fix. I just wanted to check that it was cool with you before I did more work. :)
